---
# file: allservers.yml
- name: Install the software package in all cloud servers
  hosts: allservers
  become: yes
  become_user: root
  gather_facts: no
  roles:
    - updatecache
    - sharedsoftware
    - machinelearningpackage
    - mountvolume
    - installcouchdb
    - pushfiles
    - startharvester